image: python:3.7-slim-stretch

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

stages:
  - test
  - quality_assurance
  - deploy

services:
  - docker:dind

before_script:
  - pip3 install ../graph-flow -e ".[testing]"

unit_tests:
  stage: test
  script: python setup.py test
  only:
    - merge_requests
    - master

static_analysis:
  stage: quality_assurance
  script:
    - pylint setup.py
    - pylint graphflow
    - pylint tests
    - vulture graphflow --min-confidence 65
    - vulture tests --min-confidence 65
    - bandit graphflow -lll -r
  only:
    - merge_requests
    - master

