image: python:3.7-slim-stretch

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

stages:
  - test
  - quality_assurance
  - deploy

services:
  - docker:dind

before_script:
  - pip3 install ../graph-flow -e ".[testing]"

unit_tests:
  stage: test
  script: python setup.py test
  only:
    - merge_requests
    - master

static_analysis:
  stage: quality_assurance
  script:
    - pylint setup.py
    - pylint graphflow
    - pylint tests
    - vulture graphflow --min-confidence 65
    - vulture tests --min-confidence 65
    - bandit graphflow -lll -r
  only:
    - merge_requests
    - master

deploy_registry:
  image: docker:stable
  stage: deploy
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/io-2019-networks/graph-flow/image:latest .
    - docker push $CI_REGISTRY/io-2019-networks/graph-flow/image:latest
  only:
    - master
