image: python:3.7.1

stages:
  - test
  - quality_assurance

before_script:
  - pip3 install ../graph-flow -e ".[testing]"

unit_tests:
  stage: test
  script: python setup.py test
  only:
    - merge_requests

static_analysis:
  stage: quality_assurance
  script:
    - pylint setup.py
    - pylint graphflow
    - pylint tests
    - vulture graphflow
    - vulture tests
    - bandit graphflow -lll
  only:
    - merge_requests
